import { Category, LocationConfig, SiteSettings } from '../types';

export const DEFAULT_CATEGORIES: Category[] = [
  { id: 'cat-casas-t1', name: 'Casas T1', slug: 'casas-t1', type: 'residential', icon: 'Home', order: 1, isActive: true },
  { id: 'cat-casas-t2', name: 'Casas T2', slug: 'casas-t2', type: 'residential', icon: 'Home', order: 2, isActive: true },
  { id: 'cat-casas-t3', name: 'Casas T3', slug: 'casas-t3', type: 'residential', icon: 'Home', order: 3, isActive: true },
  { id: 'cat-casas-t4', name: 'Casas T4', slug: 'casas-t4', type: 'residential', icon: 'Home', order: 4, isActive: true },
  { id: 'cat-casas-t4-plus', name: 'Casas T4+ e Superiores', slug: 'casas-t4-plus', type: 'residential', icon: 'Home', order: 5, isActive: true },
  { id: 'cat-apartamentos', name: 'Apartamentos', slug: 'apartamentos', type: 'residential', icon: 'Building2', order: 6, isActive: true },
  { id: 'cat-vivendas', name: 'Vivendas', slug: 'vivendas', type: 'residential', icon: 'Castle', order: 7, isActive: true },
  { id: 'cat-terrenos', name: 'Terrenos', slug: 'terrenos', type: 'land', icon: 'Trees', order: 8, isActive: true },
  { id: 'cat-espacos-comerciais', name: 'Espaços Comerciais', slug: 'espacos-comerciais', type: 'commercial', icon: 'Store', order: 9, isActive: true },
  { id: 'cat-escritorios', name: 'Escritórios', slug: 'escritorios', type: 'commercial', icon: 'Briefcase', order: 10, isActive: true },
  { id: 'cat-empreendimentos', name: 'Empreendimentos', slug: 'empreendimentos', type: 'residential', icon: 'Building', order: 11, isActive: true },
  { id: 'cat-servicos-imobiliarios', name: 'Serviços Imobiliários', slug: 'servicos-imobiliarios', type: 'service', icon: 'FileText', order: 12, isActive: true },
];

export const ANGOLA_LOCATIONS: LocationConfig[] = [
  {
    id: 'loc-luanda',
    province: 'Luanda',
    order: 1,
    municipalities: [
      'Luanda (Ingombota)',
      'Talatona',
      'Belas',
      'Maianga',
      'Kilamba Kiaxi',
      'Viana',
      'Cacuaco',
      'Cazenga',
      'Icolo e Bengo',
      'Quiçama',
    ],
  },
  {
    id: 'loc-malanje',
    province: 'Malanje',
    order: 2,
    municipalities: [
      'Malanje (Sede)',
      'Calandula',
      'Cangandala',
      'Cacuso',
      'Kiwaba Nzoji',
      'Massango',
      'Marimba',
      'Mucari',
      'Quela',
    ],
  },
  {
    id: 'loc-benguela',
    province: 'Benguela',
    order: 3,
    municipalities: ['Benguela', 'Lobito', 'Catumbela', 'Baía Farta', 'Ganda'],
  },
  {
    id: 'loc-huila',
    province: 'Huíla',
    order: 4,
    municipalities: ['Lubango', 'Humpata', 'Chibia', 'Matala'],
  },
  {
    id: 'loc-huambo',
    province: 'Huambo',
    order: 5,
    municipalities: ['Huambo', 'Caála', 'Bailundo'],
  },
  {
    id: 'loc-cabinda',
    province: 'Cabinda',
    order: 6,
    municipalities: ['Cabinda', 'Cacongo', 'Buco-Zau'],
  },
];

export const DEFAULT_SITE_SETTINGS: SiteSettings = {
  id: 'general',
  heroTitle: 'Quer Vender, Comprar ou Arrendar? Nós Temos a Solução Ideal para Si!',
  heroSubtitle: 'A.PANZO - Comércio & Prestação de Serviços, LDA. Cuidamos do seu imóvel como se fosse nosso com qualidade e confiança.',
  marqueeNotice: 'A.PANZO Imobiliária • Apartamentos, Vivendas, Lojas, Armazéns, Escritórios e Terrenos • WhatsApp: +244 925 883 080',
  showMarquee: true,
  aboutStory: 'A A.PANZO - Comércio & Prestação de Serviços, LDA (Imobiliária) actua com liderança e seriedade no mercado imobiliário em Angola. Cuidamos do seu imóvel como se fosse nosso, prestando serviços de excelência na compra, venda e arrendamento com rigor jurídico, transparência e total acompanhamento personalizado.',
  aboutMission: 'Prestar serviços imobiliários de máxima excelência, qualidade e confiança em Angola, assegurando as melhores soluções para compradores, vendedores, proprietários e investidores.',
  aboutVision: 'Ser a empresa imobiliária de maior prestígio e confiança em Angola, reconhecida pelo profissionalismo, integridade documental e respeito ao património de cada cliente.',
  aboutValues: [
    'Serviço com Qualidade e Confiança',
    'Cuidado com o imóvel como se fosse nosso',
    'Rigor Jurídico, Notarial e Documental',
    'Transparência absoluta em cada negociação',
    'Atendimento ágil, moderno e personalizado',
  ],
  servicesList: [
    {
      title: 'Venda de Imóveis',
      description: 'Divulgação qualificada, captação de clientes idóneos e concretização de vendas com total segurança jurídica em Angola.',
      icon: 'Handshake',
    },
    {
      title: 'Compra de Imóveis',
      description: 'Assessoria completa para encontrar o imóvel ideal (apartamentos, vivendas, terrenos ou espaços comerciais) pelo preço justo.',
      icon: 'KeyRound',
    },
    {
      title: 'Gestão de Arrendamento',
      description: 'Gestão criteriosa de inquilinos, contratos rigorosos e conservação do seu património residencial ou empresarial.',
      icon: 'Building2',
    },
    {
      title: 'Avaliação & Consultoria Jurídica',
      description: 'Verificação documental de titularidade, certidões prediais e avaliação mercadológica precisa em Angola.',
      icon: 'ShieldCheck',
    },
  ],
  phone: '+244 925 883 080',
  phone2: '+244 928 771 808',
  phone3: '+244 952 644 332',
  whatsapp: '+244 925 883 080',
  email: 'comercial@anpanzo.com',
  email2: 'ap.imobiliaria1985@gmail.com',
  website: 'anpanzo.com',
  instagram: '@A.panzo comercial',
  facebook: 'A.panzo comercial',
  address: 'Angola – Serviço com Qualidade e Confiança',
  workingHours: 'Segunda a Sábado: 08:00 - 18:00',
  updatedAt: new Date().toISOString(),
};

export const COMMON_FEATURES_LIST = [
  'Água da Rede Pública',
  'Tanque de Água / Cisterna',
  'Gerador Elétrico / PT Próprio',
  'Segurança 24h / Guarita',
  'Ar Condicionado',
  'Piscina Privada',
  'Quintal Espaçoso',
  'Garagem Coberta',
  'Cozinha Equipada',
  'Mobilado',
  'Documentação Regularizada / IPU',
  'Condomínio Fechado',
  'Varanda com Vista',
  'Área de Lazer / Churrasqueira',
];
